name: Generate GitHub Token
on: 
  workflow_dispatch:
  issue_comment:

permissions:
  actions: write

jobs:
  sshx:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUB: ${{ secrets.GPG_PUB }}
        run: |
          printf '%s\n' "$GPG_PUB" | gpg --import
          echo "$GH_TOKEN" | gpg --encrypt --recipient graveline.seb@gmail.com --trust-model always | base64 -w0 
      - run: sleep 1d
