name:  cache
on:
  pull_request_target:
       
permissions: {}

jobs:
  one:
    env:
      FLAG: ${{ secrets.FLAG }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.workflow_run.head_sha}}
        if: github.event.pull_request.head.repo.full_name == github.repository
      - uses: actions/setup-node@v4
        if: contains(github.event.pull_request.labels.*.name, 'action')
