name: pull_request_target
on:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - locked
      - unlocked
      - enqueued
      - dequeued
      - milestoned
      - demilestoned
      - ready_for_review
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
permissions: {}

jobs:
  one:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "${{ secrets.FLAG }}"
