name: pull_request
on:
  pull_request:
    
permissions: {}

jobs:
  one:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "non default"
