name: workflow_run
on:
  workflow_run:
    workflows:
      - trigger
      # - discussion
      # - fork
      # - gollum
      # - issue_comment
      # - issue
      # - milestone
      # - pull_request
      # - pull_request_review
      - pull_request_review_comment
      # - pull_request_target
      # - push
    
permissions: {}

jobs:
  one:
    runs-on: ubuntu-22.04
    env:
      FLAG: ${{ secrets.FLAG }}
    steps:
      - name: Event
        env:
          WORKFLOW_NAME: ${{ github.event.workflow.name }}
        run: echo "$WORKFLOW_NAME"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - run: bash test.sh
